name: Backend Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install bun
        run: npm install -g bun

      - name: Install dependencies using bunx
        run: bun install

      - name: Run Prisma Migrate Deploy
        run: bunx prisma migrate deploy
